driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      network:
      - ["private_network", {ip: "192.168.33.10"}]
  - name: centos-7.2
    driver:
      network:
      - ["private_network", {ip: "192.168.33.11"}]
  - name: debian-8.2
    driver:
      box: bento/debian-8.2
      network:
      - ["private_network", {ip: "192.168.33.12"}]

suites:
  - name: default
    run_list: ["recipe[php_chef]"]
    attributes:
      mariadb:
        server_root_password: 'p4assch3fphp'
        server_debian_password: 'p4assch3fphp'
        server_repl_password: 'replpass'
