driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-8.2
    driver:
      box: bento/debian-8.2
      network:
      - ["private_network", {ip: "192.168.10.12"}]

suites:
  - name: default
    run_list: ["recipe[php_chef]"]
    attributes:
      mysql:
        server_root_password: 'p4assch3fphp'
        server_debian_password: 'p4assch3fphp'
        server_repl_password: 'replpass'
