driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver:
      box: boxcutter/ubuntu1604
      network:
      - ["private_network", { ip: "192.168.33.10"}]
  - name: ubuntu-14.04
    driver:
      box: boxcutter/ubuntu1404
      network:
      - ["private_network", {ip: "192.168.33.11"}]
  - name: centos-7.2
    driver:
      box: boxcutter/centos72
      network:
      - ["private_network", {ip: "192.168.33.12"}]
  - name: debian-8.2
    driver:
      box: boxcutter/debian82
      network:
      - ["private_network", {ip: "192.168.33.13"}]

suites:
  - name: default
    run_list: ["recipe[php_chef]"]
    attributes:
      mariadb:
        allow_root_pass_change: true
        server_root_password: 'p4assch3fphp'
        server_debian_password: 'p4assch3fphp'
        server_repl_password: 'replpass'
        debian:
          user: 'root'
          password: 'p4assch3fphp'
