---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-8.2
    driver:
      box: bento/debian-8.2
      network:
      - ["private_network", {ip: "192.168.22.33"}]
  # - name: ubuntu-14.04
  #   driver:
  #     box: bento/ubuntu-14.04
  #     network:
  #       - ["private_network", { ip: "33.33.33.10" }
  # - name: centos-6.7
  #   driver:
  #     box: bento/centos-6.7
  #     network:
  #       - ["private_network", { ip: "33.33.33.10" }

suites:
  - name: default
    run_list: ["recipe[chef_php]"]
    attributes:
      mysql:
        server_root_password: 'p4assch3fphp',
        server_debian_password: 'p4assch3fphp',
        server_repl_password: 'replpass'
